#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIRECTORY=/opt/vps-agent
ENVIRONMENT_FILE=/etc/vps-agent/vps-agent.env
SERVICE_USER=agent
REPOSITORY_URL=''
REPOSITORY_REF=main
BACKEND_ID=''
BACKEND_TOKEN=''
BACKEND_NAME=''
BACKEND_TAGS=''
REDIS_URL=''
TUNNEL_TOKEN=''
CONTROL_PLANE_URL=''
PUBLIC_BASE_URL=''
QUICK_TUNNEL=false
ALLOW_APT=false

usage() {
  cat <<'EOF'
Usage: sudo bash install-agent.sh --repo <git-url> --backend-token <token> --redis-url <redis-url> --control-plane-url <url> (--public-url <url> | --quick-tunnel) [options]

Required:
  --repo <git-url>          Git repository containing this project.
  --backend-token <token>   Registration secret configured in the Cloudflare Worker.
  --redis-url <url>         Redis URL: prefer rediss://; redis:// is allowed only on a private/restricted network.
  --control-plane-url <url> Worker URL used for self-registration.
  --public-url <url>        Stable Agent URL. Required for managed/manual Tunnel mode.
  --quick-tunnel            Create a temporary trycloudflare.com URL automatically.

Optional:
  --backend-name <name>     Display name for the node card; defaults to this VPS hostname.
  --backend-id <id>         Pre-provisioned ID (generated by the managed Tunnel flow).
  --tags <csv>              Comma-separated tags, such as production,full.
  --tunnel-token <token>    Remotely managed Cloudflare Tunnel token.
  --ref <git-ref>           Git branch/tag, default: main.
  --allow-apt               Permit sudo apt-get for the agent. This is root-equivalent.
EOF
}

while (($#)); do
  case "$1" in
    --repo) REPOSITORY_URL=${2:?missing value for --repo}; shift 2 ;;
    --backend-id) BACKEND_ID=${2:?missing value for --backend-id}; shift 2 ;;
    --backend-token) BACKEND_TOKEN=${2:?missing value for --backend-token}; shift 2 ;;
    --backend-name) BACKEND_NAME=${2:?missing value for --backend-name}; shift 2 ;;
    --tags) BACKEND_TAGS=${2:?missing value for --tags}; shift 2 ;;
    --redis-url) REDIS_URL=${2:?missing value for --redis-url}; shift 2 ;;
    --tunnel-token) TUNNEL_TOKEN=${2:?missing value for --tunnel-token}; shift 2 ;;
    --control-plane-url) CONTROL_PLANE_URL=${2:?missing value for --control-plane-url}; shift 2 ;;
    --public-url) PUBLIC_BASE_URL=${2:?missing value for --public-url}; shift 2 ;;
    --quick-tunnel) QUICK_TUNNEL=true; shift ;;
    --ref) REPOSITORY_REF=${2:?missing value for --ref}; shift 2 ;;
    --allow-apt) ALLOW_APT=true; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if ((EUID != 0)); then
  echo 'Run this installer with sudo.' >&2
  exit 1
fi
if [[ -z $REPOSITORY_URL || -z $BACKEND_TOKEN || -z $REDIS_URL || -z $CONTROL_PLANE_URL ]]; then
  echo 'Missing a required option.' >&2
  usage >&2
  exit 2
fi
if [[ $REDIS_URL != redis://* && $REDIS_URL != rediss://* ]]; then
  echo 'Redis URL must use redis:// or rediss://.' >&2
  exit 2
fi
if [[ $REDIS_URL == redis://* ]]; then
  echo 'Warning: redis:// is plaintext. Use it only when Redis is private/restricted and never exposed to the public Internet.' >&2
fi
if [[ $CONTROL_PLANE_URL != https://* ]]; then
  echo 'Control-plane URL must use HTTPS.' >&2
  exit 2
fi
if [[ $QUICK_TUNNEL == true && ( -n $PUBLIC_BASE_URL || -n $TUNNEL_TOKEN ) ]]; then
  echo '--quick-tunnel cannot be combined with --public-url or --tunnel-token.' >&2
  exit 2
fi
if [[ $QUICK_TUNNEL == false && $PUBLIC_BASE_URL != https://* ]]; then
  echo 'Managed/manual Tunnel mode requires a public Agent URL using HTTPS.' >&2
  exit 2
fi
if [[ -z $BACKEND_ID ]]; then
  BACKEND_ID="vps-$(dd if=/dev/urandom bs=6 count=1 2>/dev/null | od -An -tx1 | tr -d '[:space:]')"
elif [[ ! $BACKEND_ID =~ ^[a-z0-9-]{1,64}$ ]]; then
  echo 'Backend ID must match [a-z0-9-]{1,64}.' >&2
  exit 2
fi
if [[ -z $BACKEND_NAME ]]; then BACKEND_NAME=$(hostname -s); fi
if [[ -e $APP_DIRECTORY ]]; then
  echo "$APP_DIRECTORY already exists; refusing to overwrite an existing installation." >&2
  exit 1
fi

apt-get update
apt-get install -y ca-certificates curl git build-essential python3 sudo xz-utils

install_node_lts() {
  local machine_architecture node_architecture manifest node_file node_version archive_url
  machine_architecture=$(uname -m)
  case "$machine_architecture" in
    x86_64) node_architecture=x64 ;;
    aarch64|arm64) node_architecture=arm64 ;;
    *) echo "Unsupported Node.js architecture: $machine_architecture" >&2; exit 1 ;;
  esac
  manifest=$(mktemp)
  curl --fail --location --output "$manifest" \
    https://nodejs.org/download/release/latest-v22.x/SHASUMS256.txt
  node_file=$(awk "/node-v.*-linux-$node_architecture\\.tar\\.xz$/ { print \$2; exit }" "$manifest")
  if [[ -z $node_file ]]; then
    echo 'Could not determine the latest Node.js 22 LTS archive.' >&2
    exit 1
  fi
  node_version=${node_file%-linux-*}
  archive_url="https://nodejs.org/download/release/latest-v22.x/$node_file"
  curl --fail --location --output "/tmp/$node_file" "$archive_url"
  (cd /tmp && grep " $node_file$" "$manifest" | sha256sum -c -)
  install -d /usr/local/lib/nodejs
  tar -xJf "/tmp/$node_file" -C /usr/local/lib/nodejs
  ln -sfn "/usr/local/lib/nodejs/$node_version/bin/node" /usr/local/bin/node
  ln -sfn "/usr/local/lib/nodejs/$node_version/bin/npm" /usr/local/bin/npm
  ln -sfn "/usr/local/lib/nodejs/$node_version/bin/npx" /usr/local/bin/npx
  rm -f "$manifest" "/tmp/$node_file"
}

if ! command -v node >/dev/null || ! node -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 22 ? 0 : 1)'; then
  install_node_lts
fi
install_pnpm() {
  local installed_version
  installed_version=$(pnpm --version 2>/dev/null || true)
  if [[ $installed_version == 10.14.0 ]]; then return; fi
  echo 'Installing pnpm 10.14.0...'
  npm install --global --force pnpm@10.14.0
  installed_version=$(pnpm --version)
  if [[ $installed_version != 10.14.0 ]]; then
    echo "Expected pnpm 10.14.0, found $installed_version." >&2
    exit 1
  fi
}

install_pnpm
git clone --depth 1 --branch "$REPOSITORY_REF" "$REPOSITORY_URL" "$APP_DIRECTORY"
cd "$APP_DIRECTORY"
pnpm install --frozen-lockfile
pnpm --filter @vps-agent/contracts build
pnpm --filter @vps-agent/vps-agent build

useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER" 2>/dev/null || true
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" /var/lib/vps-agent/logs
install -d /etc/vps-agent /etc/systemd/system/vps-agent.service.d
chown -R "$SERVICE_USER:$SERVICE_USER" "$APP_DIRECTORY"

install -m 640 -o root -g "$SERVICE_USER" /dev/null "$ENVIRONMENT_FILE"
cat >"$ENVIRONMENT_FILE" <<EOF
BACKEND_ID=$BACKEND_ID
BACKEND_NAME=$BACKEND_NAME
BACKEND_TAGS=$BACKEND_TAGS
BACKEND_SHARED_TOKEN=$BACKEND_TOKEN
CONTROL_PLANE_URL=$CONTROL_PLANE_URL
PUBLIC_BASE_URL=$PUBLIC_BASE_URL
REGISTRATION_INTERVAL_SECONDS=300
LISTEN_HOST=127.0.0.1
LISTEN_PORT=3100
REDIS_URL=$REDIS_URL
DATABASE_PATH=/var/lib/vps-agent/agent.db
LOG_DIR=/var/lib/vps-agent/logs
WORKER_CONCURRENCY=1
RUN_MODE=all
DEFAULT_PROFILE=full
PI_COMMAND=pi
PI_COMMAND_ARGS_JSON=[]
EOF
chmod 640 "$ENVIRONMENT_FILE"

install -m 644 "$APP_DIRECTORY/apps/vps-agent/systemd/vps-agent.service" /etc/systemd/system/vps-agent.service
NODE_BINARY=$(command -v node)
cat >/etc/systemd/system/vps-agent.service.d/node.conf <<EOF
[Service]
ExecStart=
ExecStart=$NODE_BINARY /opt/vps-agent/apps/vps-agent/dist/main.js
EOF

if [[ $ALLOW_APT == true ]]; then
  cat >/etc/sudoers.d/vps-agent-apt <<EOF
# apt-get can execute package maintainer scripts as root. Treat this as root access.
$SERVICE_USER ALL=(root) NOPASSWD: /usr/bin/apt-get
EOF
  chmod 440 /etc/sudoers.d/vps-agent-apt
  visudo -cf /etc/sudoers.d/vps-agent-apt
  cat >/etc/systemd/system/vps-agent.service.d/allow-apt.conf <<'EOF'
[Service]
NoNewPrivileges=false
EOF
fi

systemctl daemon-reload
systemctl enable --now vps-agent
curl --fail --silent --show-error \
  -H "Authorization: Bearer $BACKEND_TOKEN" \
  http://127.0.0.1:3100/health
echo

install_cloudflared() {
  MACHINE_ARCHITECTURE=$(dpkg --print-architecture)
  case "$MACHINE_ARCHITECTURE" in
    amd64|arm64) ;;
    *) echo "Unsupported cloudflared architecture: $MACHINE_ARCHITECTURE" >&2; exit 1 ;;
  esac
  if ! command -v cloudflared >/dev/null; then
    PACKAGE_PATH=/tmp/cloudflared-linux-$MACHINE_ARCHITECTURE.deb
    curl --fail --location --output "$PACKAGE_PATH" \
      "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-$MACHINE_ARCHITECTURE.deb"
    apt-get install -y "$PACKAGE_PATH"
    rm -f "$PACKAGE_PATH"
  fi
}

install_quick_tunnel_service() {
  install -d /usr/local/lib/vps-agent
  cat >/usr/local/lib/vps-agent/quick-tunnel.sh <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

ENVIRONMENT_FILE=/etc/vps-agent/vps-agent.env
while true; do
  cloudflared tunnel --no-autoupdate --url http://127.0.0.1:3100 2>&1 | while IFS= read -r line; do
    printf '%s\n' "$line"
    if [[ $line =~ https://[-a-z0-9]+\.trycloudflare\.com ]]; then
      public_url=${BASH_REMATCH[0]}
      sed -i "s|^PUBLIC_BASE_URL=.*|PUBLIC_BASE_URL=$public_url|" "$ENVIRONMENT_FILE"
      systemctl try-restart vps-agent
    fi
  done || true
  sleep 3
done
EOF
  chmod 700 /usr/local/lib/vps-agent/quick-tunnel.sh
  cat >/etc/systemd/system/vps-agent-quick-tunnel.service <<'EOF'
[Unit]
Description=VPS Agent temporary Cloudflare Quick Tunnel
After=network-online.target vps-agent.service
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/lib/vps-agent/quick-tunnel.sh
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now vps-agent-quick-tunnel
}

if [[ $QUICK_TUNNEL == true ]]; then
  install_cloudflared
  install_quick_tunnel_service
  echo 'Quick Tunnel is starting. It will print a temporary trycloudflare.com URL and register the Agent automatically.'
elif [[ -n $TUNNEL_TOKEN ]]; then
  install_cloudflared
  if ! systemctl is-enabled --quiet cloudflared 2>/dev/null; then
    cloudflared service install "$TUNNEL_TOKEN"
  fi
  systemctl restart vps-agent
  echo "Managed Tunnel installed for $PUBLIC_BASE_URL."
fi

echo "VPS Agent $BACKEND_ID is running."
if [[ $ALLOW_APT == true ]]; then
  echo 'apt enabled: Agent tasks may run sudo apt-get install -y <package>; this is root-equivalent access.'
fi
