#!/usr/bin/env bash
set -Eeuo pipefail

INSTALL_ROOT=/opt/vacps
DATA_DIRECTORY=/var/lib/vacps
ENVIRONMENT_DIRECTORY=/etc/vacps
ENVIRONMENT_FILE=/etc/vacps/vacps.env
TUNNEL_TOKEN_FILE=/etc/vacps/tunnel.env
TUNNEL_SERVICE=vacps-tunnel
TUNNEL_UNIT_FILE=/etc/systemd/system/vacps-tunnel.service
SERVICE_USER=''
SERVICE_GROUP=''
SERVICE_HOME=''
NATIVE_VERSION=0.1.10
NATIVE_INSTALL_DIR=$INSTALL_ROOT/native
NATIVE_BIN_NAME=vacps-agent-linux-x86_64
NATIVE_SCRIPT_NAME=vacps.mjs
# GitHub owner/repo used for native release assets (override with --native-github-repo).
NATIVE_GITHUB_REPO=Ykmmj/vacps
BACKEND_ID=''
REGISTRATION_TOKEN=''
BACKEND_NAME=''
BACKEND_TAGS=''
TUNNEL_TOKEN=''
CONTROL_PLANE_URL=''
CONTROL_PLANE_PUBLIC_KEY=''
PUBLIC_BASE_URL=''
QUICK_TUNNEL=false
ALLOW_ROOT=false
RESUME_INSTALL=false
PURGE_DATA=false
REMOVE_MANAGED_TUNNEL=false
HEALTH_CHECK_TIMEOUT_SECONDS=90
HEALTH_CHECK_DELAY_SECONDS=2

usage() {
  cat <<'EOF'
Usage: sudo bash agent.sh <command> [options]

Commands:
  install      Install VACPS on this host (or resume an interrupted install).
  upgrade      Download a native release and restart. Keeps identity, env, and data.
  reinstall    Remove the service (data preserved by default), then install again.
  uninstall    Stop and remove the service and local configuration.

Run "sudo bash agent.sh <command> --help" for command-specific options.

Examples:
  curl -fsSL https://<control-plane>/agent.sh | sudo bash -s -- install --registration-token ...
  curl -fsSL https://<control-plane>/agent.sh | sudo bash -s -- upgrade
  curl -fsSL https://<control-plane>/agent.sh | sudo bash -s -- reinstall --registration-token ...
  curl -fsSL https://<control-plane>/agent.sh | sudo bash -s -- uninstall
EOF
}

install_usage() {
  cat <<'EOF'
Usage: sudo bash agent.sh install [options]

Required:
  --registration-token <token>
                            One-time registration token from the control panel (valid 10 minutes).
  --control-plane-url <url> Worker URL used for self-registration.
  --control-plane-public-key <key>
                            Ed25519 public key returned with the registration token.
  --public-url <url>        Stable Agent URL. Required for managed/manual Tunnel mode.
  --quick-tunnel            Create a temporary trycloudflare.com URL automatically.

Release options:
  --native-version <ver>    GitHub release version (default: 0.1.10 → tag vacps-native-v0.1.10).
  --native-github-repo <o/r>
                            owner/repo for release assets (default: Ykmmj/vacps).

Optional:
  --backend-name <name>     Display name for the node card; defaults to this VPS hostname.
  --backend-id <id>         Pre-provisioned ID (generated by the managed Tunnel flow).
  --tags <csv>              Comma-separated tags, such as production,full.
  --tunnel-token <token>    Remotely managed Cloudflare Tunnel token.
  --allow-root              Permit passwordless root command execution. Disabled by default.
EOF
}

upgrade_usage() {
  cat <<'EOF'
Usage: sudo bash agent.sh upgrade [options]

Updates an existing VACPS installation and restarts the service.
Preserves BACKEND_ID, Ed25519 identity, control-plane settings, task data, and logs.
A new registration token is not required.

Downloads the selected vacps-native release tarball and replaces the installed files.

Optional:
  --native-version <ver>    Native release version to install.
  --native-github-repo <o/r>
                            Override release GitHub repo.
  --control-plane-url <url> Refresh CONTROL_PLANE_URL in the env file.
  --control-plane-public-key <key>
                            Refresh CONTROL_PLANE_PUBLIC_KEY in the env file.
  --allow-root              Enable passwordless root command execution.
  --help, -h                Show this help message.
EOF
}

reinstall_usage() {
  cat <<'EOF'
Usage: sudo bash agent.sh reinstall [uninstall-options] --registration-token <token> ...

Stops and removes the current service (same defaults as uninstall: data is
preserved), then runs a full install with the given options.
A fresh registration token is required.

Uninstall options (before or mixed with install options):
  --purge-data              Delete /var/lib/vacps before reinstalling.
  --remove-managed-tunnel   Accepted for compatibility; vacps-tunnel is always removed on uninstall.

Install options: same as "agent.sh install --help".
EOF
}

uninstall_usage() {
  cat <<'EOF'
Usage: sudo bash agent.sh uninstall [options]

Stops and removes the Vacps service, its configuration, vacps-tunnel /
vacps-quick-tunnel helpers, and the optional root sudoers rule. Task records
and logs are preserved by default. Host-level
cloudflared (other tunnels) is never modified.

Options:
  --purge-data              Delete /var/lib/vacps, including SQLite task records and logs.
  --remove-managed-tunnel   Accepted for compatibility; vacps-tunnel is always removed.
  --help, -h                Show this help message.
EOF
}

require_root() {
  if ((EUID != 0)); then
    echo 'Run this command with sudo.' >&2
    return 1
  fi
}

b64url_encode() {
  openssl base64 -A | tr '+/' '-_' | tr -d '='
}

generate_agent_identity_openssl() {
  local dir
  dir=$(mktemp -d)
  openssl genpkey -algorithm ED25519 -out "$dir/key.pem" >/dev/null 2>&1
  AGENT_PRIVATE_KEY=$(openssl pkey -in "$dir/key.pem" -outform DER 2>/dev/null | b64url_encode)
  # Ed25519 SPKI DER ends with 0x00 0x20 + 32-byte raw public key.
  AGENT_PUBLIC_KEY=$(openssl pkey -in "$dir/key.pem" -pubout -outform DER 2>/dev/null | tail -c 32 | b64url_encode)
  rm -rf "$dir"
}

generate_agent_identity() {
  generate_agent_identity_openssl
  if [[ ! $AGENT_PRIVATE_KEY =~ ^[A-Za-z0-9_-]{64,256}$ || ! $AGENT_PUBLIC_KEY =~ ^[A-Za-z0-9_-]{43}$ ]]; then
    echo 'Could not generate a local Ed25519 Agent identity.' >&2
    exit 1
  fi
}

native_release_tarball_url() {
  local version=$1
  printf 'https://github.com/%s/releases/download/vacps-native-v%s/vacps-native-%s-linux-x86_64.tar.gz\n' \
    "$NATIVE_GITHUB_REPO" "$version" "$version"
}

install_native_binaries() {
  local version=${1:-$NATIVE_VERSION}
  local url tmp_dir tarball
  url=$(native_release_tarball_url "$version")
  tmp_dir=$(mktemp -d)
  tarball="$tmp_dir/vacps-native.tgz"
  echo "Downloading vacps-native v${version} from $url ..."
  if ! curl --fail --silent --show-error --location --output "$tarball" "$url"; then
    echo "Failed to download native release tarball: $url" >&2
    rm -rf "$tmp_dir"
    return 1
  fi
  tar -xzf "$tarball" -C "$tmp_dir"
  if [[ ! -f $tmp_dir/$NATIVE_BIN_NAME || ! -f $tmp_dir/$NATIVE_SCRIPT_NAME ]]; then
    echo 'Native tarball missing expected files (binary + vacps.mjs).' >&2
    rm -rf "$tmp_dir"
    return 1
  fi
  install -d -m 755 "$NATIVE_INSTALL_DIR"
  install -m 755 "$tmp_dir/$NATIVE_BIN_NAME" "$NATIVE_INSTALL_DIR/$NATIVE_BIN_NAME"
  install -m 644 "$tmp_dir/$NATIVE_SCRIPT_NAME" "$NATIVE_INSTALL_DIR/$NATIVE_SCRIPT_NAME"
  if [[ -f $tmp_dir/SHA256SUMS ]]; then
    install -m 644 "$tmp_dir/SHA256SUMS" "$NATIVE_INSTALL_DIR/SHA256SUMS"
  fi
  rm -rf "$tmp_dir"
  echo "Installed native agent to $NATIVE_INSTALL_DIR"
}

wait_for_agent_health() {
  local deadline=$((SECONDS + HEALTH_CHECK_TIMEOUT_SECONDS))
  local response=''
  while ((SECONDS < deadline)); do
    if systemctl is-active --quiet vacps; then
      echo 'VACPS service is active; it will complete signed registration in the background.'
      return 0
    fi
    if ((SECONDS < deadline)); then
      sleep "$HEALTH_CHECK_DELAY_SECONDS"
    fi
  done

  echo "VACPS did not become healthy after $HEALTH_CHECK_TIMEOUT_SECONDS seconds." >&2
  if [[ -n $response ]]; then
    echo "Last health-check error: $response" >&2
  fi
  systemctl status vacps --no-pager --full >&2 || true
  journalctl -u vacps -n 50 --no-pager >&2 || true
  return 1
}

install_cloudflared() {
  MACHINE_ARCHITECTURE=$(dpkg --print-architecture)
  case "$MACHINE_ARCHITECTURE" in
    amd64|arm64) ;;
    *) echo "Unsupported cloudflared architecture: $MACHINE_ARCHITECTURE" >&2; exit 1 ;;
  esac
  if ! command -v cloudflared >/dev/null; then
    PACKAGE_PATH=/tmp/cloudflared-linux-$MACHINE_ARCHITECTURE.deb
    curl --fail --location --output "$PACKAGE_PATH" \
      "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-$MACHINE_ARCHITECTURE.deb"
    apt-get install -y "$PACKAGE_PATH"
    rm -f "$PACKAGE_PATH"
  fi
}

# Managed Tunnel runs as an independent unit (vacps-tunnel), never as the host's
# default cloudflared.service, so other tunnels on the same VPS are left alone.
install_managed_tunnel_service() {
  local token=$1
  local cloudflared_binary
  if [[ -z $token ]]; then
    echo 'Managed Tunnel install requires a non-empty --tunnel-token.' >&2
    return 1
  fi
  install_cloudflared
  cloudflared_binary=$(command -v cloudflared)
  if [[ -z $cloudflared_binary ]]; then
    echo 'cloudflared binary not found after install.' >&2
    return 1
  fi

  # Drop Quick Tunnel helper if switching to managed mode on the same host.
  systemctl disable --now vacps-quick-tunnel 2>/dev/null || true
  rm -f /etc/systemd/system/vacps-quick-tunnel.service /usr/local/lib/vacps/quick-tunnel.sh

  install -d -m 750 "$ENVIRONMENT_DIRECTORY"
  # EnvironmentFile: only the first '=' separates key and value (token may end with '=').
  install -m 600 -o root -g root /dev/null "$TUNNEL_TOKEN_FILE"
  printf 'TUNNEL_TOKEN=%s\n' "$token" >"$TUNNEL_TOKEN_FILE"

  cat >"$TUNNEL_UNIT_FILE" <<EOF
[Unit]
Description=Vacps managed Cloudflare Tunnel
Documentation=https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$TUNNEL_TOKEN_FILE
ExecStart=$cloudflared_binary tunnel --no-autoupdate run --token \${TUNNEL_TOKEN}
Restart=always
RestartSec=5
# Keep this connector isolated from any host-level cloudflared.service.

[Install]
WantedBy=multi-user.target
EOF
  chmod 644 "$TUNNEL_UNIT_FILE"
  systemctl daemon-reload
  systemctl enable --now "$TUNNEL_SERVICE"

  local deadline=$((SECONDS + 60))
  while ((SECONDS < deadline)); do
    if systemctl is-active --quiet "$TUNNEL_SERVICE"; then
      echo "vacps-tunnel is active; Managed Tunnel should show as Healthy for $PUBLIC_BASE_URL."
      return 0
    fi
    sleep 2
  done
  echo 'vacps-tunnel did not become active within 60 seconds.' >&2
  systemctl status "$TUNNEL_SERVICE" --no-pager --full >&2 || true
  journalctl -u "$TUNNEL_SERVICE" -n 50 --no-pager >&2 || true
  return 1
}

install_quick_tunnel_service() {
  local agent_port=3100
  install -d /usr/local/lib/vacps
  # Expand agent_port into the helper (not quoted heredoc).
  cat >/usr/local/lib/vacps/quick-tunnel.sh <<EOF
#!/usr/bin/env bash
set -Eeuo pipefail

ENVIRONMENT_FILE=/etc/vacps/vacps.env
AGENT_LOCAL_URL=http://127.0.0.1:${agent_port}
while true; do
  cloudflared tunnel --no-autoupdate --url "\$AGENT_LOCAL_URL" 2>&1 | while IFS= read -r line; do
    printf '%s\n' "\$line"
    if [[ \$line =~ https://[-a-z0-9]+\\.trycloudflare\\.com ]]; then
      public_url=\${BASH_REMATCH[0]}
      if grep -q '^PUBLIC_BASE_URL=' "\$ENVIRONMENT_FILE" 2>/dev/null; then
        sed -i "s|^PUBLIC_BASE_URL=.*|PUBLIC_BASE_URL=\$public_url|" "\$ENVIRONMENT_FILE"
      else
        printf 'PUBLIC_BASE_URL=%s\n' "\$public_url" >>"\$ENVIRONMENT_FILE"
      fi
      # Reload EnvironmentFile so the agent re-registers with the new public URL.
      systemctl try-restart vacps
    fi
  done || true
  sleep 3
done
EOF
  chmod 700 /usr/local/lib/vacps/quick-tunnel.sh
  cat >/etc/systemd/system/vacps-quick-tunnel.service <<'EOF'
[Unit]
Description=VACPS temporary Cloudflare Quick Tunnel
After=network-online.target vacps.service
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/lib/vacps/quick-tunnel.sh
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now vacps-quick-tunnel
  echo "Quick Tunnel helper targets native Agent port $agent_port."
}

# Resolve the account that invoked the deployment. sudo sets SUDO_USER to the
# original login account; direct root execution therefore intentionally selects
# root. New installations persist this identity, and upgrades retain it.
resolve_service_identity() {
  local configured_user=''
  local candidate
  local passwd_entry

  if [[ -f $ENVIRONMENT_FILE ]]; then
    configured_user=$(sed -n 's/^VACPS_SERVICE_USER=//p' "$ENVIRONMENT_FILE" | head -n 1)
  fi
  candidate=${configured_user:-${SUDO_USER:-}}
  if [[ -z $candidate ]]; then candidate=$(id -un); fi

  if [[ ! $candidate =~ ^[A-Za-z_][A-Za-z0-9_.-]*[$]?$ ]] || ! id "$candidate" >/dev/null 2>&1; then
    echo "Deployment user '$candidate' is not an existing local account." >&2
    return 1
  fi
  passwd_entry=$(getent passwd "$candidate")
  SERVICE_USER=${passwd_entry%%:*}
  SERVICE_GROUP=$(id -gn "$SERVICE_USER")
  SERVICE_HOME=$(printf '%s\n' "$passwd_entry" | cut -d: -f6)

  if [[ $SERVICE_HOME != /* || ! -d $SERVICE_HOME ]]; then
    echo "Deployment user '$SERVICE_USER' must already have an absolute, existing HOME directory." >&2
    return 1
  fi
  if ! runuser -u "$SERVICE_USER" -- test -x "$SERVICE_HOME"; then
    echo "Deployment user '$SERVICE_USER' cannot access HOME '$SERVICE_HOME'." >&2
    return 1
  fi

  # A deployment invoked directly from a root login necessarily runs the
  # service as root; report that capability truthfully without a sudoers rule.
  if [[ $SERVICE_USER == root ]]; then ALLOW_ROOT=true; fi

  echo "VACPS service identity: $SERVICE_USER:$SERVICE_GROUP (HOME=$SERVICE_HOME)."
}

# Optional runtime deps for tools (root provisioning; agent does not need sudo).
install_agent_runtime_packages() {
  export DEBIAN_FRONTEND=noninteractive
  # ripgrep accelerates files.grep/glob; runtime falls back if install fails.
  apt-get install -y --no-install-recommends ripgrep 2>/dev/null || \
    echo 'Note: ripgrep not installed; files.grep will use a slower fallback.' >&2
  # git enables MCP vacps.git.* helpers (compositions over /usr/bin/git + command.exec).
  # Capability probe is authoritative if this optional package install fails.
  apt-get install -y --no-install-recommends git 2>/dev/null || \
    echo 'Note: git not installed; vacps.git tools remain unavailable until /usr/bin/git is present.' >&2
}

write_systemd_unit() {
  # Port 3100 matches control-plane managed tunnel ingress (http://127.0.0.1:3100).
  local agent_port=3100
  install -d /etc/systemd/system/vacps.service.d
  cat >/etc/systemd/system/vacps.service <<EOF
[Unit]
Description=VACPS Backend (native)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_GROUP
WorkingDirectory=$NATIVE_INSTALL_DIR
Environment=HOME=$SERVICE_HOME
Environment=USER=$SERVICE_USER
Environment=LOGNAME=$SERVICE_USER
Environment=SHELL=/bin/bash
EnvironmentFile=$ENVIRONMENT_FILE
Environment=VACPS_LISTEN_HOST=127.0.0.1
Environment=VACPS_LISTEN_PORT=$agent_port
ExecStart=$NATIVE_INSTALL_DIR/$NATIVE_BIN_NAME --script $NATIVE_INSTALL_DIR/$NATIVE_SCRIPT_NAME --data-dir $DATA_DIRECTORY
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=false
ReadWritePaths=$DATA_DIRECTORY $SERVICE_HOME $NATIVE_INSTALL_DIR

[Install]
WantedBy=multi-user.target
EOF
  # Remove obsolete installer-owned drop-ins before recreating current policy.
  rm -f \
    /etc/systemd/system/vacps.service.d/node.conf \
    /etc/systemd/system/vacps.service.d/native.conf \
    /etc/systemd/system/vacps.service.d/protect-home.conf \
    /etc/systemd/system/vacps.service.d/allow-apt.conf \
    /etc/systemd/system/vacps.service.d/allow-root.conf
  rm -f /etc/sudoers.d/vacps-apt /etc/sudoers.d/vacps-root

  if [[ $ALLOW_ROOT == true && $SERVICE_USER != root ]]; then
    cat >/etc/sudoers.d/vacps-root <<EOF
# Explicit opt-in: authenticated VACPS commands may execute arbitrary root operations.
$SERVICE_USER ALL=(root) NOPASSWD: ALL
EOF
    chmod 440 /etc/sudoers.d/vacps-root
    visudo -cf /etc/sudoers.d/vacps-root
    cat >/etc/systemd/system/vacps.service.d/allow-root.conf <<'EOF'
[Service]
NoNewPrivileges=false
EOF
  fi
}

is_installed_layout() {
  [[ -x $NATIVE_INSTALL_DIR/$NATIVE_BIN_NAME &&
    -f $NATIVE_INSTALL_DIR/$NATIVE_SCRIPT_NAME &&
    -f $ENVIRONMENT_FILE &&
    -f /etc/systemd/system/vacps.service ]]
}

require_installed() {
  if ! is_installed_layout; then
    echo "No native VACPS installation found at $NATIVE_INSTALL_DIR. Run install first." >&2
    return 1
  fi
}

parse_install_options() {
  while (($#)); do
    case "$1" in
      --backend-id) BACKEND_ID=${2:?missing value for --backend-id}; shift 2 ;;
      --registration-token) REGISTRATION_TOKEN=${2:?missing value for --registration-token}; shift 2 ;;
      --backend-name) BACKEND_NAME=${2:?missing value for --backend-name}; shift 2 ;;
      --tags) BACKEND_TAGS=${2:?missing value for --tags}; shift 2 ;;
      --tunnel-token) TUNNEL_TOKEN=${2:?missing value for --tunnel-token}; shift 2 ;;
      --control-plane-url) CONTROL_PLANE_URL=${2:?missing value for --control-plane-url}; shift 2 ;;
      --control-plane-public-key) CONTROL_PLANE_PUBLIC_KEY=${2:?missing value for --control-plane-public-key}; shift 2 ;;
      --public-url) PUBLIC_BASE_URL=${2:?missing value for --public-url}; shift 2 ;;
      --quick-tunnel) QUICK_TUNNEL=true; shift ;;
      --native-version) NATIVE_VERSION=${2:?missing value for --native-version}; shift 2 ;;
      --native-github-repo) NATIVE_GITHUB_REPO=${2:?missing value for --native-github-repo}; shift 2 ;;
      --allow-root) ALLOW_ROOT=true; shift ;;
      --purge-data) PURGE_DATA=true; shift ;;
      --remove-managed-tunnel) REMOVE_MANAGED_TUNNEL=true; shift ;;
      --help|-h) return 100 ;;
      *) echo "Unknown option: $1" >&2; return 2 ;;
    esac
  done
}

validate_install_options() {
  if [[ -z $REGISTRATION_TOKEN || -z $CONTROL_PLANE_URL || -z $CONTROL_PLANE_PUBLIC_KEY ]]; then
    echo 'Missing a required option (registration-token / control-plane-url / control-plane-public-key).' >&2
    install_usage >&2
    return 2
  fi
  if [[ -z $NATIVE_VERSION ]]; then
    echo '--native-version is empty.' >&2
    return 2
  fi
  if [[ ! $NATIVE_GITHUB_REPO =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
    echo '--native-github-repo must look like owner/repo.' >&2
    return 2
  fi
  if [[ $CONTROL_PLANE_URL != https://* ]]; then
    echo 'Control-plane URL must use HTTPS.' >&2
    return 2
  fi
  if [[ ! $REGISTRATION_TOKEN =~ ^[A-Za-z0-9_-]{43}$ ]]; then
    echo 'Registration token must be a base64url 32-byte value.' >&2
    return 2
  fi
  if [[ ! $CONTROL_PLANE_PUBLIC_KEY =~ ^[A-Za-z0-9_-]{43}$ ]]; then
    echo 'Control-plane public key must be a base64url Ed25519 public key.' >&2
    return 2
  fi
  if [[ $QUICK_TUNNEL == true && ( -n $PUBLIC_BASE_URL || -n $TUNNEL_TOKEN ) ]]; then
    echo '--quick-tunnel cannot be combined with --public-url or --tunnel-token.' >&2
    return 2
  fi
  if [[ $QUICK_TUNNEL == false && $PUBLIC_BASE_URL != https://* ]]; then
    echo 'Managed/manual Tunnel mode requires a public Agent URL using HTTPS.' >&2
    return 2
  fi
  if [[ -n $BACKEND_ID && ! $BACKEND_ID =~ ^[a-z0-9-]{1,64}$ ]]; then
    echo 'Backend ID must match [a-z0-9-]{1,64}.' >&2
    return 2
  fi
  if [[ -z $BACKEND_NAME ]]; then BACKEND_NAME=$(hostname -s); fi
}

uninstall_agent() {
  while (($#)); do
    case "$1" in
      --purge-data) PURGE_DATA=true; shift ;;
      --remove-managed-tunnel) REMOVE_MANAGED_TUNNEL=true; shift ;;
      --help|-h) uninstall_usage; return 0 ;;
      *) echo "Unknown uninstall option: $1" >&2; uninstall_usage >&2; return 2 ;;
    esac
  done
  require_root
  systemctl disable --now vacps 2>/dev/null || true
  systemctl disable --now vacps-quick-tunnel 2>/dev/null || true
  systemctl disable --now "$TUNNEL_SERVICE" 2>/dev/null || true
  # Never touch the host's cloudflared.service — Vacps only owns vacps-tunnel.
  if [[ $REMOVE_MANAGED_TUNNEL == true ]]; then
    echo 'Note: --remove-managed-tunnel is accepted for compatibility; vacps-tunnel is always removed. Host cloudflared is never modified.'
  fi

  rm -f /etc/systemd/system/vacps.service
  rm -rf /etc/systemd/system/vacps.service.d
  rm -f /etc/systemd/system/vacps-quick-tunnel.service
  rm -f "$TUNNEL_UNIT_FILE"
  rm -f /usr/local/lib/vacps/quick-tunnel.sh
  rmdir /usr/local/lib/vacps 2>/dev/null || true
  rm -f /etc/sudoers.d/vacps-apt /etc/sudoers.d/vacps-root
  # ENVIRONMENT_DIRECTORY includes tunnel.env; remove after stopping the unit.
  rm -rf "$ENVIRONMENT_DIRECTORY" "$INSTALL_ROOT"
  if [[ $PURGE_DATA == true ]]; then
    rm -rf "$DATA_DIRECTORY"
  else
    echo "Preserved $DATA_DIRECTORY (SQLite task records and logs). Re-run with --purge-data to delete it."
  fi
  systemctl daemon-reload
  systemctl reset-failed vacps vacps-quick-tunnel "$TUNNEL_SERVICE" 2>/dev/null || true
  echo 'Vacps service files have been removed (including vacps-tunnel when present).'
  echo 'Host cloudflared (if any) was left installed and unchanged.'
}

refresh_env_keys() {
  if [[ -n $CONTROL_PLANE_URL ]]; then
    if grep -q '^CONTROL_PLANE_URL=' "$ENVIRONMENT_FILE"; then
      sed -i "s|^CONTROL_PLANE_URL=.*|CONTROL_PLANE_URL=$CONTROL_PLANE_URL|" "$ENVIRONMENT_FILE"
    else
      printf 'CONTROL_PLANE_URL=%s\n' "$CONTROL_PLANE_URL" >>"$ENVIRONMENT_FILE"
    fi
  fi
  if [[ -n $CONTROL_PLANE_PUBLIC_KEY ]]; then
    if grep -q '^CONTROL_PLANE_PUBLIC_KEY=' "$ENVIRONMENT_FILE"; then
      sed -i "s|^CONTROL_PLANE_PUBLIC_KEY=.*|CONTROL_PLANE_PUBLIC_KEY=$CONTROL_PLANE_PUBLIC_KEY|" "$ENVIRONMENT_FILE"
    else
      printf 'CONTROL_PLANE_PUBLIC_KEY=%s\n' "$CONTROL_PLANE_PUBLIC_KEY" >>"$ENVIRONMENT_FILE"
    fi
  fi
}

remove_obsolete_env_keys() {
  # Native process options are CLI-only. Listening remains JavaScript product
  # policy through VACPS_LISTEN_HOST / VACPS_LISTEN_PORT.
  sed -i \
    -e '/^AGENT_RUNTIME=/d' \
    -e '/^VACPS_DATA_DIR=/d' \
    -e '/^VACPS_SCRIPT=/d' \
    "$ENVIRONMENT_FILE"
  rm -f "$ENVIRONMENT_DIRECTORY/agent-runtime"
}

persist_service_policy() {
  sed -i -e '/^VACPS_SERVICE_USER=/d' -e '/^VACPS_ALLOW_ROOT=/d' "$ENVIRONMENT_FILE"
  printf 'VACPS_SERVICE_USER=%s\n' "$SERVICE_USER" >>"$ENVIRONMENT_FILE"
  if [[ $ALLOW_ROOT == true ]]; then
    printf 'VACPS_ALLOW_ROOT=1\n' >>"$ENVIRONMENT_FILE"
  else
    printf 'VACPS_ALLOW_ROOT=0\n' >>"$ENVIRONMENT_FILE"
  fi
  chown root:root "$ENVIRONMENT_FILE"
  chmod 600 "$ENVIRONMENT_FILE"
}

upgrade_agent() {
  while (($#)); do
    case "$1" in
      --native-version) NATIVE_VERSION=${2:?missing value for --native-version}; shift 2 ;;
      --native-github-repo) NATIVE_GITHUB_REPO=${2:?missing value for --native-github-repo}; shift 2 ;;
      --control-plane-url) CONTROL_PLANE_URL=${2:?missing value for --control-plane-url}; shift 2 ;;
      --control-plane-public-key) CONTROL_PLANE_PUBLIC_KEY=${2:?missing value for --control-plane-public-key}; shift 2 ;;
      --allow-root) ALLOW_ROOT=true; shift ;;
      --help|-h) upgrade_usage; return 0 ;;
      *) echo "Unknown upgrade option: $1" >&2; upgrade_usage >&2; return 2 ;;
    esac
  done
  require_root
  require_installed

  if [[ -z $NATIVE_VERSION ]]; then
    echo '--native-version is empty.' >&2
    return 2
  fi
  if [[ ! $NATIVE_GITHUB_REPO =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
    echo '--native-github-repo must look like owner/repo.' >&2
    return 2
  fi

  if grep -q '^VACPS_ALLOW_ROOT=1$' "$ENVIRONMENT_FILE"; then ALLOW_ROOT=true; fi
  resolve_service_identity
  persist_service_policy

  if [[ -n $CONTROL_PLANE_URL && $CONTROL_PLANE_URL != https://* ]]; then
    echo 'Control-plane URL must use HTTPS.' >&2
    return 2
  fi
  if [[ -n $CONTROL_PLANE_PUBLIC_KEY && ! $CONTROL_PLANE_PUBLIC_KEY =~ ^[A-Za-z0-9_-]{43}$ ]]; then
    echo 'Control-plane public key must be a base64url Ed25519 public key.' >&2
    return 2
  fi

  BACKEND_ID=$(sed -n 's/^BACKEND_ID=//p' "$ENVIRONMENT_FILE" | head -n 1)
  if [[ -z $BACKEND_ID || ! $BACKEND_ID =~ ^[a-z0-9-]{1,64}$ ]]; then
    echo "Could not recover a valid Backend ID from $ENVIRONMENT_FILE." >&2
    return 1
  fi

  systemctl stop vacps 2>/dev/null || true
  apt-get update
  apt-get install -y ca-certificates curl openssl sudo

  echo "Upgrading native VACPS installation for $BACKEND_ID (version: $NATIVE_VERSION)."
  install_native_binaries "$NATIVE_VERSION"
  refresh_env_keys
  remove_obsolete_env_keys
  install_agent_runtime_packages
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$DATA_DIRECTORY"
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$DATA_DIRECTORY/logs"
  chown -R "$SERVICE_USER:$SERVICE_GROUP" "$DATA_DIRECTORY" "$NATIVE_INSTALL_DIR"
  write_systemd_unit
  systemctl daemon-reload
  systemctl enable vacps
  systemctl restart vacps
  wait_for_agent_health
  echo "VACPS $BACKEND_ID upgraded successfully (native v$NATIVE_VERSION)."

  if [[ $ALLOW_ROOT == true ]]; then
    echo 'root execution enabled: authenticated Agent commands may run sudo -n without a password.'
  fi
}

write_environment_file() {
  local allow_root_value=0
  if [[ $ALLOW_ROOT == true ]]; then allow_root_value=1; fi
  install -d /etc/vacps
  # systemd reads EnvironmentFile before applying User=/Group=. Keep Agent
  # identity keys private to root instead of exposing them to a shared primary
  # group that the deployment user may belong to.
  install -m 600 -o root -g root /dev/null "$ENVIRONMENT_FILE"
  # Always write PUBLIC_BASE_URL= so quick-tunnel sed can update the line later.
  # For --quick-tunnel the value starts empty; discovery fills it before re-register.
  cat >"$ENVIRONMENT_FILE" <<EOF
VACPS_SERVICE_USER=$SERVICE_USER
VACPS_ALLOW_ROOT=$allow_root_value
BACKEND_ID=$BACKEND_ID
BACKEND_NAME=$BACKEND_NAME
BACKEND_TAGS=$BACKEND_TAGS
AGENT_PRIVATE_KEY=$AGENT_PRIVATE_KEY
AGENT_PUBLIC_KEY=$AGENT_PUBLIC_KEY
CONTROL_PLANE_PUBLIC_KEY=$CONTROL_PLANE_PUBLIC_KEY
REGISTRATION_TOKEN=$REGISTRATION_TOKEN
CONTROL_PLANE_URL=$CONTROL_PLANE_URL
PUBLIC_BASE_URL=$PUBLIC_BASE_URL
REGISTRATION_INTERVAL_SECONDS=300
TELEMETRY_FALLBACK_INTERVAL_SECONDS=120
VACPS_LISTEN_HOST=127.0.0.1
VACPS_LISTEN_PORT=3100
DATABASE_PATH=$DATA_DIRECTORY/agent.db
LOG_DIR=$DATA_DIRECTORY/logs
EOF
  rm -f "$ENVIRONMENT_DIRECTORY/agent-runtime"
  chmod 600 "$ENVIRONMENT_FILE"
}

recover_or_allocate_backend_id() {
  if [[ $RESUME_INSTALL == true ]]; then
    EXISTING_BACKEND_ID=$(sed -n 's/^BACKEND_ID=//p' "$ENVIRONMENT_FILE" | head -n 1)
    if [[ -z $EXISTING_BACKEND_ID || ! $EXISTING_BACKEND_ID =~ ^[a-z0-9-]{1,64}$ ]]; then
      echo "Could not recover a valid Backend ID from $ENVIRONMENT_FILE." >&2
      exit 1
    fi
    if [[ -n $BACKEND_ID && $BACKEND_ID != "$EXISTING_BACKEND_ID" ]]; then
      echo "Backend ID $BACKEND_ID does not match the existing installation ($EXISTING_BACKEND_ID)." >&2
      exit 1
    fi
    BACKEND_ID=$EXISTING_BACKEND_ID
    echo "Resuming the existing VACPS installation for $BACKEND_ID."
  elif [[ -z $BACKEND_ID ]]; then
    BACKEND_ID="vacps-$(dd if=/dev/urandom bs=6 count=1 2>/dev/null | od -An -tx1 | tr -d '[:space:]')"
  fi
}

load_or_generate_identity() {
  AGENT_PRIVATE_KEY=''
  AGENT_PUBLIC_KEY=''
  if [[ $RESUME_INSTALL == true ]]; then
    AGENT_PRIVATE_KEY=$(sed -n 's/^AGENT_PRIVATE_KEY=//p' "$ENVIRONMENT_FILE" | head -n 1)
    AGENT_PUBLIC_KEY=$(sed -n 's/^AGENT_PUBLIC_KEY=//p' "$ENVIRONMENT_FILE" | head -n 1)
  fi
  if [[ ! ${AGENT_PRIVATE_KEY} =~ ^[A-Za-z0-9_-]{64,256}$ || ! ${AGENT_PUBLIC_KEY} =~ ^[A-Za-z0-9_-]{43}$ ]]; then
    generate_agent_identity
  fi
}

finish_tunnel_and_report() {
  if [[ $QUICK_TUNNEL == true ]]; then
    install_cloudflared
    install_quick_tunnel_service
    echo 'Quick Tunnel is starting. It will print a temporary trycloudflare.com URL and register the Agent automatically.'
  elif [[ -n $TUNNEL_TOKEN ]]; then
    install_managed_tunnel_service "$TUNNEL_TOKEN"
    systemctl restart vacps
    echo "Managed Tunnel (unit $TUNNEL_SERVICE) installed for $PUBLIC_BASE_URL."
  else
    echo 'Warning: no --tunnel-token or --quick-tunnel was provided; the Agent registered a public URL but no Vacps tunnel connector was configured.' >&2
  fi

  echo "Native VACPS $BACKEND_ID is running."
  if [[ $ALLOW_ROOT == true ]]; then
    echo 'root execution enabled: authenticated Agent commands may run sudo -n without a password.'
  fi
}

install_agent() {
  require_root
  resolve_service_identity
  validate_install_options

  apt-get update
  apt-get install -y ca-certificates curl openssl sudo

  if [[ -e $INSTALL_ROOT || -f $ENVIRONMENT_FILE ]]; then
    if ! is_installed_layout; then
      # Allow an empty installation root before its native directory is created.
      if [[ -d $INSTALL_ROOT && -z $(find "$INSTALL_ROOT" -mindepth 1 -maxdepth 1 -print -quit) && ! -f $ENVIRONMENT_FILE ]]; then
        :
      elif [[ -f $ENVIRONMENT_FILE && -d $NATIVE_INSTALL_DIR ]]; then
        RESUME_INSTALL=true
      else
        echo "Existing files under $INSTALL_ROOT are not a resumable native install." >&2
        echo 'Use "agent.sh reinstall" after uninstall, or remove them manually.' >&2
        exit 1
      fi
    else
      RESUME_INSTALL=true
    fi
  fi

  recover_or_allocate_backend_id
  load_or_generate_identity

  if [[ $RESUME_INSTALL == false ]] || [[ ! -x $NATIVE_INSTALL_DIR/$NATIVE_BIN_NAME ]]; then
    install_native_binaries "$NATIVE_VERSION"
  fi

  install_agent_runtime_packages
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$DATA_DIRECTORY"
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$DATA_DIRECTORY/logs"
  install -d /etc/vacps /etc/systemd/system/vacps.service.d
  chown -R "$SERVICE_USER:$SERVICE_GROUP" "$DATA_DIRECTORY" "$NATIVE_INSTALL_DIR"

  write_environment_file
  write_systemd_unit
  systemctl daemon-reload
  systemctl enable vacps
  systemctl restart vacps
  wait_for_agent_health
  finish_tunnel_and_report
}

reinstall_agent() {
  local parse_status=0
  parse_install_options "$@" || parse_status=$?
  if ((parse_status == 100)); then
    reinstall_usage
    return 0
  fi
  if ((parse_status != 0)); then
    reinstall_usage >&2
    return "$parse_status"
  fi
  require_root
  validate_install_options

  echo 'Reinstalling VACPS: removing the current service, then installing again.'
  # PURGE_DATA / REMOVE_MANAGED_TUNNEL already parsed above.
  uninstall_args=()
  if [[ $PURGE_DATA == true ]]; then uninstall_args+=(--purge-data); fi
  if [[ $REMOVE_MANAGED_TUNNEL == true ]]; then uninstall_args+=(--remove-managed-tunnel); fi
  uninstall_agent "${uninstall_args[@]}"

  # Reset flags that install_agent must treat as a fresh install.
  RESUME_INSTALL=false
  install_agent
}

# --- entrypoint ----------------------------------------------------------------

COMMAND=${1:-}
if [[ $COMMAND == --help || $COMMAND == -h || $COMMAND == help ]]; then
  usage
  exit 0
fi
if [[ -z $COMMAND || $COMMAND == -* ]]; then
  # Backward compatible: options without an explicit command mean install.
  COMMAND=install
else
  shift
fi

case "$COMMAND" in
  install)
    parse_status=0
    parse_install_options "$@" || parse_status=$?
    if ((parse_status == 100)); then install_usage; exit 0; fi
    if ((parse_status != 0)); then install_usage >&2; exit "$parse_status"; fi
    # Reject reinstall-only flags on plain install.
    if [[ $PURGE_DATA == true || $REMOVE_MANAGED_TUNNEL == true ]]; then
      echo 'Use "agent.sh reinstall" or "agent.sh uninstall" for --purge-data / --remove-managed-tunnel.' >&2
      exit 2
    fi
    install_agent
    ;;
  upgrade)
    upgrade_agent "$@"
    ;;
  reinstall)
    reinstall_agent "$@"
    ;;
  uninstall)
    uninstall_agent "$@"
    ;;
  *)
    echo "Unknown command: $COMMAND" >&2
    usage >&2
    exit 2
    ;;
esac
